### ISSUE TITLE
Transposing numpy array input causes failure in write()

### ISSUE THREAD

**Issue by mccalluc** [drj11/pypng#91]
Transposing the numpy input array causes an error when I try to save the file.

```python
# Normally it works:
>>> a = np.array([[0, 1], [2, 3]]).astype(np.int8)
>>> i = png.from_array(a, mode='L')
>>> i.save('/tmp/i.png')

# Transposing breaks it:
>>> a_trans = np.transpose(a)
>>> i_trans = png.from_array(a_trans, mode='L')
>>> i_trans.save('/tmp/i_trans.png')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/chuck/anaconda3/envs/hubmap/lib/python3.6/site-packages/png.py", line 1371, in save
    w.write(file, self.rows)
  File "/Users/chuck/anaconda3/envs/hubmap/lib/python3.6/site-packages/png.py", line 648, in write
    nrows = self.write_passes(outfile, check_rows(rows))
  File "/Users/chuck/anaconda3/envs/hubmap/lib/python3.6/site-packages/png.py", line 682, in write_passes
    return self.write_packed(outfile, rows)
  File "/Users/chuck/anaconda3/envs/hubmap/lib/python3.6/site-packages/png.py", line 723, in write_packed
    data.extend(row)
TypeError: can't set bytearray slice from numpy.ndarray

# Dump to array and reload is a work-around:
>>> a_trans_wrapped = np.array(a_trans.tolist()).astype(np.int8)
>>> i_trans_wrapped = png.from_array(a_trans_wrapped, mode='L')
>>> i_trans_wrapped.save('/tmp/i_trans_wrapped.png')
```

```
$ pip show pypng
Name: pypng
Version: 0.0.19
```

**Comment by drj11** [comment]
oh numpy. Always be adding vector-like objects that aren't quite like Python lists.

**Comment by drj11** [comment]
I've added a test (second try) and the tests fails with the same error. https://github.com/drj11/pypng/pull/92

Will probably be a few days before I look at this again.

I had a quick look at the code.
The crux of the matter is that it fails on this line: `data.extend(row)`. `data` is a `bytearray` (it's the filtered bytes just before they are compressed) and `row` is some sort of `numpy` array.

There used to be all sorts of extra code here to cope with numpy arrays because those arrays caused this code to fail (basically, coerce the numpy array to a Python list first). But I recently removed all that code, and numpy has improved to the point where the extra code wasn't necessary.

Except for transposed arrays it seems.

It might not be easy to fix without adding extra checking code, and I don't really want to add it back.

**Comment by mccalluc** [comment]
For my purposes, I'm happy with the work-around, dumping it to a list and reloading... If it turns out to be tricky, a stopgap might be just to rethrow the error, and point to this issue. Your call: Thanks for looking into it!

**Comment by drj11** [comment]
workaround: A `.copy()` is sufficient:

    a_trans = a.transpose().copy()

**Comment by drj11** [comment]
I increasingly feel that this is a numpy bug. Example that avoids PyPNG altogether:

```
import numpy

a = numpy.array([[1,2,3],[4,5,6]], dtype=numpy.uint8)
b = bytearray()
b.extend(a) # works
b.extend(a.transpose()) # does not work
```

I'm not going to change the PyPNG code to address this, but I'll add a note to the documentation, and hopefully this issue will be here forever so that people can find the `TypeError: can't set bytearray slice from numpy.ndarray` error via search.

**Comment by drj11** [comment]
I added this note to the documentation: https://github.com/drj11/pypng/commit/c4935f49d4ab1a66983e33ede232ca2f79d34a60

**Comment by glenfletcher** [comment]
_I was just looking at using PyPNG for saving some png images, and found the like to this issue in the docs._

This is not a bug in numpy, rather a feature that's not supported by bytearray

from python docs:

> ### [Bytes and Bytearray Operations](https://docs.python.org/3/library/stdtypes.html#bytearray)
> 
> Both bytes and bytearray objects support the common sequence operations. They interoperate not just with operands of the same type, but with any bytes-like object. Due to this flexibility, they can be freely mixed in operations without causing errors.

and

> ### [bytes-like object](https://docs.python.org/3/library/stdtypes.html#typesseq-common)
>  An object that supports the Buffer Protocol and can export a C-contiguous buffer. This includes all bytes, bytearray, and array.array objects, as well as many common memoryview objects. Bytes-like objects can be used for various operations that work with binary data; these include compression, saving to a binary file, and sending over a socket.
>
>  Some operations need the binary data to be mutable. The documentation often refers to these as “read-write bytes-like objects”. Example mutable buffer objects include bytearray and a memoryview of a bytearray. Other operations require the binary data to be stored in immutable objects (“read-only bytes-like objects”); examples of these include bytes and a memoryview of a bytes object.

The problem is transpose returns a non-C-contiguous interface to the same [memory buffer](https://docs.python.org/3/c-api/buffer.html#bufferobjects), see [numpy views](https://numpy.org/doc/stable/glossary.html#term-view)

```py
>>> import numpy as np
>>> a = np.array([[0, 1], [2, 3]]).astype(np.int8)
>>> a_trans = np.transpose(a)
>>> a.__array_interface__
{'data': (3105285390496, False), 'strides': None, 'descr': [('', '|i1')], 'typestr': '|i1', 'shape': (2, 2), 'version': 3}
>>> a_trans.__array_interface__
{'data': (3105285390496, False), 'strides': (1, 2), 'descr': [('', '|i1')], 'typestr': '|i1', 'shape': (2, 2), 'version': 3}
>>> id(a)
3103777193296
>>> id(a_trans.base)
3103777193296
>>> a.swapaxes(1, 0).__array_interface__
{'data': (3105285390496, False), 'strides': (1, 2), 'descr': [('', '|i1')], 'typestr': '|i1', 'shape': (2, 2), 'version': 3}
>>> memoryview(a).c_contiguous
True
>>> memoryview(a_trans).c_contiguous
False
```

**Comment by drj11** [comment]
This is excellent background research, thanks @glenfletcher .
